package N101_Submodel_LH_Wing_Rib_150_A {
    private import Geometry::*;
    private import ISQ::*;

    part Part_1 {
        part bounding_box_0 :> RectangularCuboid {
            :>> length = 1528.243223 [mm];
            :>> width = 645.579367 [mm];
            :>> height = 392.631699 [mm];
        }
    }
    part Part_2 {
        part bounding_box_1 :> RectangularCuboid {
            :>> length = 1453.056751 [mm];
            :>> width = 578.624396 [mm];
            :>> height = 356.591963 [mm];
        }
    }
}
